### ISSUE TITLE
Login failed for user '<token-identified principal>' DACPAC Publish with AccessToken authentication 

### ISSUE THREAD

**Issue by paulgartner1** [microsoft/DacFx#315]
- SqlPackage Version: 162.0.52 & 161.8089.0 & 161.6374.0
- .NET Framework (Windows-only) or .NET Core: 
- Environment (local platform and source/target platforms): Local (windows) & Azure DevOps (windows)

**Steps to Reproduce:**

1. Have existing Azure SQL DB to which login works 
2. Obtain DB access token for Azure AD user or service principal
3. Publish DACPAC supplying `/AccessToken:` property
4. Error `Login failed for user '<token-identified principal>'` 

Commands
```
Connect-AzAccount 

$accessToken = (Get-AzAccessToken -Resource "https://database.windows.net/").Token

sqlpackage `
  /at:$accessToken `
  /Action:Publish `
  /SourceFile:"Test.dacpac" `
  /TargetConnectionString:"Server=tcp:{server_name}.database.windows.net,1433;Initial Catalog={database_name};MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30" `
  /Diagnostics:True `
  /p:BlockOnPossibleDataLoss=False /p:CreateNewDatabase=True

```

Error:
```
Microsoft.Data.Tools.Diagnostics.Tracer Error: 19 : 2023-08-15T13:13:40 : Retry requested: Retry count = 1. Delay = 00:00:00, SQL Error Code = -2146232060, SQL Error Number 
= 18456, Can retry error = False, Will retry = False Microsoft.Data.SqlClient.SqlException (0x80131904): Login failed for user '<token-identified principal>'.
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserS
tateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.TdsParser.Run(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStat
eObject stateObj)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.CompleteLogin(Boolean enlistOK)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.AttemptOneLogin(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean ignoreSniOpenTimeo
ut, TimeoutTimer timeout, Boolean withFailover)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.LoginNoFailover(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInst
ance, SqlConnectionString connectionOptions, SqlCredential credential, TimeoutTimer timeout)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.OpenLoginEnlist(TimeoutTimer timeout, SqlConnectionString connectionOptions, SqlCredential credential, String newPass
word, SecureString newSecurePassword, Boolean redirectedUserInstance)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object prov
iderInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Bo
olean applyTransientFaultHandling, String accessToken, DbConnectionPool pool)
   at Microsoft.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool
 pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptio
ns)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnec
tionInternal oldConnection, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 
retry, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbC
onnectionOptions userOptions)
   at Microsoft.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry, SqlConnectionOverrides overrides)
   at Microsoft.Data.SqlClient.SqlConnection.Open(SqlConnectionOverrides overrides)
   at Microsoft.Data.SqlClient.SqlConnection.Open()
   at Microsoft.Data.Tools.Schema.Common.SqlClient.ReliableSqlConnection.<OpenConnection>b__49_0() in C:\__w\1\s\Source\SchemaSql\Common\SqlClient\ReliableSqlConnection.cs:l
ine 419
   at Microsoft.Data.Tools.Schema.Common.SqlClient.RetryPolicy.<>c__DisplayClass25_0.<ExecuteAction>b__0(RetryState _) in C:\__w\1\s\Source\SchemaSql\Common\SqlClient\RetryP
olicy.cs:line 125
   at Microsoft.Data.Tools.Schema.Common.SqlClient.RetryPolicy.<>c__DisplayClass26_0.<ExecuteAction>b__0(RetryState retryState) in C:\__w\1\s\Source\SchemaSql\Common\SqlClie
nt\RetryPolicy.cs:line 138
   at Microsoft.Data.Tools.Schema.Common.SqlClient.RetryPolicy.ExecuteAction[R](Func`2 func, Nullable`1 token) in C:\__w\1\s\Source\SchemaSql\Common\SqlClient\RetryPolicy.cs
:line 189
ClientConnectionId:92ab5f79-9e4e-4be8-8421-2dd02028cd2e
Error Number:18456,State:1,Class:14

...

sqlpackage : *** An error occurred during deployment plan generation. Deployment cannot continue.
At line:8 char:1
+ sqlpackage `
+ ~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (*** An error oc...annot continue.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
Login failed for user '<token-identified principal>'.
```

I know the user has permissions and the accesstoken works as the below command works as expected:
```
Connect-AzAccount

$accessToken = (Get-AzAccessToken -Resource "https://database.windows.net/").Token

Invoke-Sqlcmd -AccessToken $accessToken -ServerInstance "{server_name}.database.windows.net" -Database "{database_name}" -Query "SELECT SUSER_NAME()" 
```
Table creation from `Invoke-Sqlcmd` also works.

(DacFx/SqlPackage/SSMS/Azure Data Studio)

**Comment by llali** [comment]
@paulgartner1 do you get this error after sqlpackage running for a while or immediately. When you pass a token to sqlpackage, it cannot refresh the token if it gets expired. So you want to make sure you have a token can stay valid for a long time. Better approach would be to use  other authentication types like service principals

**Comment by paulgartner1** [comment]
I discovered the dacpac I was running was creating logins requiring access to `master`. The user does not permissions to do this.
Once the logins where removed, the dacpac deployed successfully.
The presentation of the error threw me off.
