### ISSUE TITLE
Schema Compare failed: Unexpected exception ...: Unable to cast object of type 'System.Boolean' to type 'System.Int32'.

### ISSUE THREAD

**Issue by SakshiS-harma** [microsoft/DacFx#348]
This bug was first reported on ADS platform. But after an initial triage and testing, it seems to be an issue emanating from the DacFx side of the code.
** (copy of the original bug)
- Azure Data Studio Version:1.46.0
- OS Version: Windows 10 Enterprise - 10.0.19044
I have two Synapse Serverless Instances DWH Prod & UAT.

I am trying to compare schemas. Loading the servers as Source and destination Yields:

Schema Compare failed: Unexpected exception caught during population of target model: Unable to cast object of type 'System.Boolean' to type 'System.Int32'.
Unexpected exception caught during population of source model: Unable to cast object of type 'System.Boolean' to type 'System.Int32'.

Note:

 - There are no boolean or bit fields in these serverless db instances.
 - Error occurs in about 3 seconds
 - All my (6) other Serverless synapse dbs work fine.
**

**Comment by SakshiS-harma** [comment]
- The customer mentioned that this happens with two DHW DB instances. Switching source/target yields the same error.
- Similar (but not same) error is received on Visual Studio as well.
- Issue doesn't repro when same instances' dacpacs are compared (but since the changes can not be applied, going with this path isn't useful).
- Probably not a regression, customer hasn't seen this scenario work before.

**Comment by SakshiS-harma** [comment]
@pgeorge-redmond Created this issue for DacFx folks to look at. Thanks!

**Comment by pgeorge-redmond** [comment]
[DB DacPac.zip](https://github.com/microsoft/DacFx/files/12820958/DB.DacPac.zip)

Files provided

**Comment by pgeorge-redmond** [comment]
Posted in github.

P-

**Comment by SakshiS-harma** [comment]
@pgeorge-redmond Did you get any stack trace while hitting this error?
Also, we need more info to debug this particular issue, since it is not easily reproducible. If you could attach your logs to the issue (ensure no private data is in them), it would help us fix the issue much faster.

1. First open the Settings page, find the Mssql: Tracing Level setting and change that to All then restart Azure Data Studio.
2. Open command palette (Click View -> Command Palette) and run the command Developer: Set Log Level... and set the level to Trace.
3. Run the repro scenarios.
4. Collect the following logs:
Console Logs

- Open Developer Tools (Help -> Toggle Developer Tools)
- Click the Console tab
- Click in the log area and select all text (CTRL+A)
- Save this text into a file named console.log and attach it to this issue.
- Developer Tools can be closed via Help -> Toggle Developer Tools

Application Logs

- Open command palette (Click View -> Command Palette)
- Run the command: Developer: Open Logs Folder
- This will open the log folder locally. Please zip up this folder and attach it to the issue.

5. Now you can revert the Log/Tracing levels changes made in step 1 and step 2.

**Comment by gonsalu** [comment]
The problem seems to be that this query:

```
select 
    perms.class as class,
    objectpropertyex(perms.major_id, 'BaseType') as type,
    perms.major_id as majorid,
    perms.minor_id as minorid,
    perms.type + perms.state as name,
    perms.grantee_principal_id as id1,
    perms.grantor_principal_id as id2
from sys.database_permissions perms
where
    perms.major_id >= 0
```

Returns NULL for the type column for some schemas, even tho the user running the query has sysadmin permissions.

![Image](https://github.com/user-attachments/assets/e5e5fddd-9e24-499c-95f3-3f28f08a9e41)

The query seems to come from `Microsoft.Data.Tools.Schema.Sql`.

Last part of the log in `sqltools.log`:

```
24-11-21 1:07:52.7434154 pid:17920 tid:72 sqltools Verbose: 0 : eventTID:12992 <sc.SqlConfigurableRetryLogicManager.CommandProvider|INFO> Requested the CommandProvider value.
24-11-21 1:07:52.7434403 pid:17920 tid:72 sqltools Verbose: 0 : eventTID:12992 SqlCommand.RunExecuteReaderTds | Info | Object Id 210, Activity Id 85ec7d8e-2bf1-4a7d-85f1-879378e45046:7, Client Connection Id a5b53bcc-c308-41ff-ba42-feb1ffd7f635, Command executed as SQLBATCH, Command Text '
select object_id as id, 
    null as id2,
    case
        when [is_filetable] = 1 then 'UF'
        else [type]
    end as [type],
    schema_name(schema_id) as name1,
    name as name2,
    null as name3,
    null as a1,
    null as v1,
    modify_date as mod
from sys.tables
where 
    is_ms_shipped != 1

union

select object_id as id, 
    null as id2,
    case
        when [type] != 'D ' then [type]
        when parent_object_id != 0 then 'D '
        else 'LD' 
    end as [type],
    schema_name(schema_id) as name1,
    name as name2,
    null as name3,
    null as a1,
    null as v1,
    modify_date as mod
from sys.objects
where 
    type != 'S'
    and type != 'U'
    and type != 'ST'
    and is_ms_shipped != 1

union

select principal_id as id, 
    null as id2,
    type, 
    name collate Database_Default as name1, 
    null as name2, 
    null as name3,
    null as a1,
    null as v1,
    modify_date as mod
from sys.database_principals

union

select schema_id as id, 
    null as id2,
    'SCH' as type, 
    name as name1, 
    null as name2, 
    null as name3,
    principal_id as a1,
    null as v1,
    null as mod
from sys.schemas

union

select stat.object_id as id,
    stat.stats_id as id2,
    'STAT' as [type],
    schema_name(tab.schema_id) as name,
    tab.name as name2,
    stat.name as name3,
    null as a1,
    no_recompute as v1,
    null as mod
from sys.stats stat
    inner join sys.tables tab on stat.object_id = tab.object_id
where 
    stat.user_created = 1

union

select
    symmetric_key_id id,
    null as id2,
    'MK'as type,
    null as name1,
    null as name2,
    null as name3,
    principal_id as a1,
    null as v1,
    modify_date as mod
from sys.symmetric_keys
where
    name = N'##MS_DatabaseMasterKey##'


union

select
    principal_id id,
    null as id2,
    'LOG' as type,
    name as name1,
    null as name2,
    null as name3,
    null as a1,
    null as v1,
    modify_date as mod
from sys.sql_logins


select 
    perms.class as class,
    objectpropertyex(perms.major_id, 'BaseType') as type,
    perms.major_id as majorid,
    perms.minor_id as minorid,
    perms.type + perms.state as name,
    perms.grantee_principal_id as id1,
    perms.grantor_principal_id as id2
from sys.database_permissions perms
where
    perms.major_id >= 0

union

select 
    cast(4 as tinyint) as class,
    'R' as type,
    roles.role_principal_id as majorid,
    roles.member_principal_id as minorid,
    'drm' as name,
    null as id1,
    null as id2
from sys.database_role_members roles 


select 
    cols.object_id as tableid,
    cols.column_id as columnid, 
    binary_checksum(cols.name) as checksum
from sys.tables tabs 
    inner join sys.columns cols  on (tabs.object_id = cols.object_id)
    inner join sys.index_columns idx_cols on (idx_cols.object_id = tabs.object_id and idx_cols.column_id = cols.column_id)
where
    tabs.is_ms_shipped = 0

' 
24-11-21 1:07:53.3073743 pid:17920 tid:72 sqltools Verbose: 0 : eventTID:12992 TdsParserStateObject.DecrementOpenResultCount | INFO | State Object Id 57, Processing Attention.
24-11-21 1:07:53.4588377 pid:17920 tid:72 sqltools Error: 0 : Failed to compare schema. Error: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.SqlServer.Dac.Compare.SchemaComparisonResult.get_IsEqual()
   at Microsoft.SqlTools.ServiceLayer.SchemaCompare.SchemaCompareService.<>c__DisplayClass9_0.<<HandleSchemaCompareRequest>b__0>d.MoveNext() in /_/src/Microsoft.SqlTools.ServiceLayer/SchemaCompare/SchemaCompareService.cs:line 91
24-11-21 1:07:53.4589553 pid:17920 tid:72 sqltools Verbose: 0 : Sending message of id[138], of type[Response] and method[schemaCompare/compare]
```
